version: '3.7'

services:
  mongodb-sharded:
    image: public.ecr.aws/bitnami/mongodb-sharded:4.4
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-sharded
      - MONGODB_SHARDING_MODE=mongos
      - MONGODB_CFG_PRIMARY_HOST=mongodb-cfg
      - MONGODB_CFG_REPLICA_SET_NAME=cfgreplicaset
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ROOT_PASSWORD=password123
    ports:
      - "27017:27017"
    depends_on:
      - mongodb-cfg

  mongodb-shard0:
    image: public.ecr.aws/bitnami/mongodb-sharded:4.4
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-shard0
      - MONGODB_SHARDING_MODE=shardsvr
      - MONGODB_MONGOS_HOST=mongodb-sharded
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=shard0
    depends_on:
      - mongodb-sharded

  mongodb-cfg:
    image: public.ecr.aws/bitnami/mongodb-sharded:4.4
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-cfg
      - MONGODB_SHARDING_MODE=configsvr
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=cfgreplicaset
  # ruby:
  #   image: public.ecr.aws/docker/library/ruby:3.0
  #   command: [ "bundle", "exec", "ruby", "mm.rb" ]
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #     - bundle:/usr/local/bundle
  #   depends_on:
  #     - mongodb-shard0
  #   environment:
  #     - "MONGODB_URL=mongodb://root:password123@mongodb-sharded:27017/test?authSource=admin"

volumes:
  bundle: null
